spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_management_tb
    password: root@1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: transaction_management-Service
server:
  port: 8081