name: build maven application

on:
  workflow_dispatch: 
    inputs:
      action:
        description: 'Action to perform on the app'
        required: true
        default: 'restart'
        type: choice
        options:
          - 'start'
          - 'stop'
          - 'restart'
      environment:
        description: 'Environment to perform the action on'
        required: true
        default: 'L3'
        type: choice
        options:
          - 'L3'
          - 'L4'
      region:
        description: 'Region to perform the action on'
        required: true
        default: 'LAS'
        type: choice
        options:
          - 'LAS'
          - 'ATL'

jobs: 
  resolve-qa-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.resolve-hosts.outputs.hosts }}
      label: ${{ steps.resolve-hosts.outputs.label }}
    steps:
      - name: Build my app
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          REGION="${{ github.event.inputs.region }}"
          ACTION="${{ github.event.inputs.action }}"
          echo "Environment: $ENVIRONMENT"
          echo "Region: $REGION"
          echo "Action: $ACTION"
          if [ "$ENVIRONMENT" = "L3" ] && [ "$REGION" = "LAS" ]; then
              echo "$ACTION app into L3 LAS region servers"
              HOSTS="${{ vars.VM_HOSTS_QA_L3_LAS }}"
              LABEL="L3"
          elif [ "$ENVIRONMENT" = "L3" ] && [ "$REGION" = "ATL" ]; then
              echo "$ACTION app into L3 ATL region servers"
              HOSTS="${{ vars.VM_HOSTS_QA_L3_ATL }}"
              LABEL="L3"
          elif [ "$ENVIRONMENT" = "L4" ] && [ "$REGION" = "LAS" ]; then
              echo "$ACTION app into L4 LAS region servers"
              HOSTS="${{ vars.VM_HOSTS_QA_L4_LAS }}"
              LABEL="L4"
          elif [ "$ENVIRONMENT" = "L4" ] && [ "$REGION" = "ATL" ]; then
              echo "$ACTION app into L4 ATL region servers"
              HOSTS="${{ vars.VM_HOSTS_QA_L4_ATL }}"
              pwd="${{ secrets.MY_SECRET }}
              LABEL="L4"
          else
              echo "Invalid environment or region"
              exit 1
          fi
          echo "Resolved Hosts: $HOSTS"
          echo "Resolved Label: $LABEL"
          echo "PWD: $pwd"
          echo "hosts=$HOSTS" >> $GITHUB_OUTPUT
          echo "label=$LABEL" >> $GITHUB_OUTPUT
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show all secrets as JSON
        run: echo '${{ toJSON(secrets) }}'
