name: build maven application

on:
  workflow_dispatch: 
    inputs: 
      level:
        description: 'Level to Deploy'
        type: choice
        required: true
        default: L3
        options:
          - L3
          - L4
      region:
        description: 'Region to deploy application'
        type: choice
        required: true
        default: 'LAS'
        options:
          - 'LAS'
          - 'ATL'
      operation:
        description: 'Operation to perform'
        type: choice
        required: true
        default: 'restart'
        options:
          - 'restart'
          - 'stop'
          - 'start'
      hosts:
        description: 'Operation to perform'
        type: choice
        required: true
        default: 'L3-QA1'
        options:
          - 'L3-LAS-QA1'
          - 'L3-LAS-QA2'
          - 'L3-ATL-QA1'
          - 'L3-ATL-QA2'
          - 'L4-LAS-QA1'
          - 'L4-LAS-QA2'
          - 'L4-ATL-QA1'
          - 'L4-ATL-QA2'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build my app
        run: echo "Building in ${{ github.event.inputs.environment }} at level ${{ github.event.inputs.level }}"
